#!/bin/bash
# bootstrap-hooks.sh
# Assembles a repo-level .pre-commit-config.yaml from shared org profiles and installs hooks.
# 
# Usage:
#   ./scripts/bootstrap-hooks.sh baseline python
#   ./scripts/bootstrap-hooks.sh baseline ansible
#   ./scripts/bootstrap-hooks.sh baseline node
#
# This script:
# 1. Fetches profiles from .github/pre-commit-profiles/
# 2. Merges them into a single .pre-commit-config.yaml
# 3. Extracts and installs venv dependencies
# 4. Installs pre-commit hooks (pre-commit and pre-push stages)

set -euo pipefail

# Configuration
GITHUB_REPO_DIR="${GITHUB_REPO_DIR:-.}"
PROFILE_DIR="$GITHUB_REPO_DIR/pre-commit-profiles"
OUTPUT_FILE=".pre-commit-config.yaml"

# Color codes for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Helper functions
log_info() { echo -e "${GREEN}[INFO]${NC} $1"; }
log_warn() { echo -e "${YELLOW}[WARN]${NC} $1"; }
log_error() { echo -e "${RED}[ERROR]${NC} $1"; }

# Validate arguments
if [[ $# -lt 1 ]]; then
    log_error "At least one profile required"
    echo "Usage: $0 <profile1> [profile2] ..."
    echo "Available profiles: baseline, python, node, ruby, ansible"
    exit 1
fi

# Validate profile directory exists
if [[ ! -d "$PROFILE_DIR" ]]; then
    log_error "Profile directory not found: $PROFILE_DIR"
    exit 1
fi

# Validate all requested profiles exist
log_info "Validating profiles..."
for profile in "$@"; do
    if [[ ! -f "$PROFILE_DIR/$profile.yaml" ]]; then
        log_error "Profile not found: $PROFILE_DIR/$profile.yaml"
        echo "Available profiles:"
        ls -1 "$PROFILE_DIR"/*.yaml 2>/dev/null | xargs -n1 basename | sed 's/\.yaml$//' || true
        exit 1
    fi
done

# Generate header
cat > "$OUTPUT_FILE" << 'EOF'
# ============================================================================
# This file is auto-generated by bootstrap-hooks.sh
# DO NOT EDIT DIRECTLY
# 
# To regenerate, run: ./scripts/bootstrap-hooks.sh <profiles>
# Management: Controlled by .github repo (https://github.com/.../.github)
# ============================================================================

EOF

# Add profiles info and fail_fast
echo "# Profiles: $*" >> "$OUTPUT_FILE"
echo "fail_fast: true" >> "$OUTPUT_FILE"
echo "repos:" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"

# Merge profiles: extract repo entries from each profile and concatenate
log_info "Merging profiles: $*"
for profile in "$@"; do
    log_info "  Adding profile: $profile"
    
    # Extract repo entries from profile starting at the first repo definition.
    awk '/^  - repo:/ { in_repos=1 } in_repos { print }' "$PROFILE_DIR/$profile.yaml" >> "$OUTPUT_FILE"
    echo "" >> "$OUTPUT_FILE"
done

# Extract venv dependencies from profiles
log_info "Extracting tool dependencies..."
VENV_DEPS=""
PIP_PACKAGES=""
GEM_PACKAGES=""
HAS_NODE_PROFILE=false

for profile in "$@"; do
    # Check for Node.js-backed hooks (baseline prettier + node profile require npm).
    if [[ "$profile" == "node" || "$profile" == "baseline" ]]; then
        HAS_NODE_PROFILE=true
    fi
    
    # Extract pip packages from Install: comments
    if grep -q "^# Install: pip install" "$PROFILE_DIR/$profile.yaml"; then
        PACKAGES=$(grep "^# Install: pip install" "$PROFILE_DIR/$profile.yaml" | sed 's/^# Install: pip install //' | head -1)
        if [[ -n "$PACKAGES" ]]; then
            log_info "  Python packages from $profile: $PACKAGES"
            PIP_PACKAGES="$PIP_PACKAGES $PACKAGES"
        fi
    fi
    
    # Extract gem packages from Install: comments
    if grep -q "^# Install: gem install" "$PROFILE_DIR/$profile.yaml"; then
        PACKAGES=$(grep "^# Install: gem install" "$PROFILE_DIR/$profile.yaml" | sed 's/^# Install: gem install //' | head -1)
        if [[ -n "$PACKAGES" ]]; then
            log_info "  Ruby gems from $profile: $PACKAGES"
            GEM_PACKAGES="$GEM_PACKAGES $PACKAGES"
        fi
    fi
done

# Warn if Node.js profile is present but npm is missing
if $HAS_NODE_PROFILE; then
    if ! command -v npm &>/dev/null; then
        log_error "Node.js profile selected but npm is not installed."
        echo "Please install Node.js (https://nodejs.org/) before running bootstrap."
        exit 1
    else
        log_info "Node.js profile detected; npm is available."
    fi
fi

# Set up venv if needed
if [[ -n "$PIP_PACKAGES" ]]; then
    log_info "Creating Python venv..."
    if [[ ! -d ".venv" ]]; then
        python3 -m venv .venv
    fi
    
    source .venv/bin/activate
    log_info "Installing Python packages: $(echo $PIP_PACKAGES | xargs)"
    pip install --upgrade pip setuptools wheel > /dev/null 2>&1
    pip install $PIP_PACKAGES
    deactivate
else
    log_warn "No Python packages to install (venv creation skipped)"
fi

# Install gems if needed (assumes Ruby environment available)
if [[ -n "$GEM_PACKAGES" ]]; then
    log_info "Installing Ruby gems: $(echo $GEM_PACKAGES | xargs)"
    gem install $GEM_PACKAGES 2>/dev/null || log_warn "gem install failed (Ruby dev environment may not be set up)"
fi

# Resolve tool binaries (prefer venv when present)
if [[ -x ".venv/bin/pre-commit" ]]; then
    PRE_COMMIT_BIN=".venv/bin/pre-commit"
else
    PRE_COMMIT_BIN="$(command -v pre-commit || true)"
fi

if [[ -x ".venv/bin/detect-secrets" ]]; then
    DETECT_SECRETS_BIN=".venv/bin/detect-secrets"
else
    DETECT_SECRETS_BIN="$(command -v detect-secrets || true)"
fi

# Install pre-commit hooks
log_info "Installing pre-commit hooks..."
if [[ -z "$PRE_COMMIT_BIN" ]]; then
    log_error "pre-commit not found. Install via: pip install pre-commit"
    exit 1
fi

"$PRE_COMMIT_BIN" install --hook-type pre-commit --hook-type pre-push --hook-type commit-msg

# Create initial .secrets.baseline if not present
if [[ ! -f ".secrets.baseline" ]]; then
    log_info "Creating initial .secrets.baseline..."
    if [[ -n "$DETECT_SECRETS_BIN" ]]; then
        "$DETECT_SECRETS_BIN" scan > .secrets.baseline 2>/dev/null || log_warn "detect-secrets scan failed; creating empty baseline"
    else
        log_warn "detect-secrets not available; creating empty baseline"
        : > .secrets.baseline
    fi
else
    log_info ".secrets.baseline already exists (skipped)"
fi

log_info "${GREEN}Bootstrap complete!${NC}"
echo ""
echo "Next steps:"
echo "  1. Review and commit .pre-commit-config.yaml"
echo "  2. Test hooks: pre-commit run --all-files"
echo "  3. Configure branch protection (require pre-commit CI check)"
echo ""
